add an instruction demo about deep learning
byzer-org/byzer-doc pull request #158
Opened 2022-01-18 14:41 UTC by ckeys

2022-01-19 05:31 UTC, ZhengshuaiPENG requested changes

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +## 准备Cifar10 图片数据集
标题和上端正文最好有空行

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +```
代码块可以标识对应的语言，这样可以渲染代码的高亮。 可以根据代码类型这写 ```shell, 或者 ```python，或 ```sql

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +```
比如这个就是典型的 ```shell 代码块

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +通过上面的指令下载好图片后，接着进行解压，然后拷贝到我们的引擎的存储上：
文字和上一段代码块之间直接最好有空行

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +#%input=raw_cifar10_table
这段代码块就是典型的 python ，可以用 ```python 来标识

2022-01-19 05:31 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +其中值得注意的是，
这种需要单独高亮让用户注意的，可以不使用代码块的方式， 使用右尖括号 > 的方式来进行渲染

2022-01-20 02:49 UTC, AndieHuang commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +通过上面的指令下载好图片后，接着进行解压，然后拷贝到我们的引擎的存储上：
will do

2022-01-20 02:49 UTC, AndieHuang commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +#%input=raw_cifar10_table
will do

2022-01-20 02:49 UTC, AndieHuang commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +```
will do

2022-01-20 02:49 UTC, AndieHuang commented on public/blog/zh-cn/2022-01-18-byzer_lang_cifar10_deeplearning.md
> +## 准备Cifar10 图片数据集
will do

2022-01-20 10:12 UTC, merged