modify the kolo-lang language specification outline
byzer-org/byzer-doc pull request #19
Opened 2021-12-09 03:34 UTC by allwefantasy

2021-12-09 05:10 UTC, ZhengshuaiPENG requested changes
1. Please modify the sidebar file in `en-us` folder
2. please change the file name under the `grammar` fodler

2021-12-09 11:00 UTC, allwefantasy commented
> 1. Please modify the sidebar file in `en-us` folder
> 2. please change the file name under the `grammar` fodler

1. Done
2. It seems no need to change the file name in grammar.

2021-12-12 07:28 UTC, ZhengshuaiPENG requested changes

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +和第一个例子有些不同，因为我们要对:a变量进行多次处理，为了使得最后的表达式更加简单，Kolo-lang支持通过select语法来做变量赋值。对于语句
关键字需要 quote 起来

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +在!if/!elif里申明的变量有效范围是整个!if/!fi区间。子if/else语句可以看到上层if/else语句的变量。 对于以下示例：
子if/else语句可以看到上层if/else语句的变量。
--> 这句话改成 “上层 if/else 语句的变量作用域是包含子分支语句的” 是不是更好

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +该语句输出为====1，我们在子if语句中使用了上面的 select产生的:newname变量。
该语句输出为====1 
--> ====1 需要 quote 起来

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/en-us/grammar/select.md
> +Kolo-lang的select 语句，兼容Spark SQL。 我们唯一做的改动是最后必须加上 `as 表名`。
加到最上面，所有关键字， 结果，代码语句，命令行等， 都需要使用 ```来进行quote

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +''';
这种稍微有些复杂的例子，最好加一些例子是做什么的说明

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +此时他的输出会是2。 但是如果你在前面加一句：
需要解释一下为什么， 这里有点难以理解 defaultParam 在这里做了什么事情

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +这个时候会输出1. 也就是用户可以通过添加set变量覆盖已经存在的变量从而控制脚本的执行。
同样的，这里我作为用户，可能就很难理解到 set a 和 set a where type 到底发生了什么事情， 参数是被覆写了还是？

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +前面我们提到,Kolo-lang支持使用自定义UDF函数，并且在!if语句中也是可以使用的。比如：
这里我理解其实是要解释清楚 UDF 的作用域是包含分支语句的逻辑代码块的？

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +因为在Kolo-lang中表的生命周期是session级别的。这意味着当一个表被使用过后，系统会自动记住。这样可以很方便的用户进行调试。 但是当使用if/else的时候则会有困惑发生。
因为在Kolo-lang中表的生命周期是session级别的。这意味着当一个表被使用过后，系统会自动记住

--> 这意味着在一个 session 中， 表都是会被自动注册在系统中的，除非被删除或者被重新定义了。

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +当一次运行的时候，系统会报错，因为没有表b. 如果我们将2==1 修改为 1==1 时，则系统正常运行。 然后我们将1==1 再次修改为2==1 此时系统依然正常运行。 因为系统记住了上次运行的b,所以虽然当前没有执行select语句，但是依然有输出，从而造成错误。
这里没有看懂。
是不是有点类似于在 java 中，如果变量在分支前定义但没有初始化，然后在某一个分支中被赋值，但另一个分支里没有被赋值，最后使用这个变量就会出错是一样的吗？

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/branch_statement.md
> +1. 请求参数设置sessionPerRequest,这样每次请求都会保证隔离。
解决办法和上面的问题是一样的，看不明白为什么这个解决办法就能解决上面的问题

2021-12-12 07:28 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/et_statement.md
> +### 概念
### 概念 
---> ### Estimator/Transformer

2021-12-12 08:35 UTC, ZhengshuaiPENG requested changes

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/commands.md
> +将一段文本当做MLSQL脚本执行：
MLSQL -> Kolo

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/commands.md
> +## !python
这些命令不要用 ## 开头， 都改成 bulletpoint 吧，用 -，不然左侧目录渲染太长了

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/commands.md
> +!delta help;
有的宏命令有 help ，有的没有，这个 help 是必须每个宏命令单独来实现吗

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/commands.md
> +
这里没有任何说明？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/commands.md
> +kafka相关的小工具
kafka 的小工具包含了哪些常用的功能？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/macro.md
> +
需要先介绍一下宏函数的一些定义，如何封装，如何实现

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/macro.md
> +1. 最后一条语句不需要分号。
突然看到最后一个语句不需要分号，那什么语句需要分号？好像没有写出来

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/macro.md
> +
还有如何引用宏函数， 宏函数的作用域是什么样的

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/macro.md
> +我们也支持命名参数：
比如这里突然出现一个命名参数，实际上就是上面宏函数的定义没有很清楚

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/outline.md
> +### 变量
这篇outline 没有什么问题，有一些疑问，对于 udf， 参数， 变量这些东西是否有特定的作用域？还是说就像解释型的语言那样，从上至下，作用域只在当前的代码 block 中生效

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/outline.md
> +安装和使用第三方插件很容易，比如：
这个插件的来源是哪里

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/register.md
> +3. 在流式计算中，注册wartermark
看起来是Register 是可以同时支持注册 UDF 和宏命令？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/register.md
> +代码片段也可以使用变量持有，然后在ScriptUDF中引用：
这个变量持有代码片段的意思是将 code snippets 作为 Value 赋给变量吗，这样这个变量就变成了一个函数？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/register.md
> +3. 在流式计算中，注册wartermark
哦，还有模型？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/save.md
> +save语法类似传统SQL中的insert语法。但同load语法一样，Kolo-lang是要面向各种数据源的。insert语法无法很好的满足该诉求，
这里需要解释说明 save to where？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/save.md
> +save语句也支持where/options条件子句。比如，我希望保存的时候，将数据按切分成十分来保存，就可以按下面的方式写：
将数据按切分成十分来保存
--> typo, 实际上就是讲数据切分成十个数据分片吧

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/save.md
> +save 也支持connect 语句的引用。
connect 语句是干什么用的？

2021-12-12 08:35 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/grammar/save.md
> +1. overwrite
1和2很好理解， 3和4 的区别是什么

2021-12-12 12:15 UTC, allwefantasy commented on kolo-lang/zh-cn/grammar/commands.md
> +!delta help;
是的

2021-12-12 12:15 UTC, allwefantasy commented on kolo-lang/zh-cn/grammar/commands.md
> +
要等相关链接ready....

2021-12-12 12:16 UTC, allwefantasy commented on kolo-lang/zh-cn/grammar/commands.md
> +kafka相关的小工具
单独的内容，这里给链接

2021-12-12 14:49 UTC, ZhengshuaiPENG approved these changes
Better then before， merge to base，I will improve later

2021-12-12 14:49 UTC, merged