change the doc content
byzer-org/byzer-doc pull request #200
Opened 2022-02-10 09:58 UTC by hellozepp

2022-02-10 11:14 UTC, chncaesar approved these changes

2022-02-15 02:40 UTC, hellozepp commented
@githubnameting PTAL

2022-02-15 02:41 UTC, hellozepp commented
@Lindsaylin PTAL

2022-02-15 02:43 UTC, ZhengshuaiPENG requested changes

2022-02-15 02:43 UTC, ZhengshuaiPENG commented on byzer-lang/zh-cn/installation/containerized_deployment/muti-continer.md
> +export KOLO_LANG_VERSION=<Byzer-lang Relase版本号>
这里还是 KOLO_LANG_VERSION？

2022-02-15 02:43 UTC, ZhengshuaiPENG commented on byzer-lang/zh-cn/installation/containerized_deployment/muti-continer.md
> +获取方式：例如最新的tag为v2.2.1，则使用版本号2.2.1，那么参数应该设置为 `export KOLO_LANG_VERSION=2.1.1`。
KOLO_LANG_VERSION

2022-02-15 02:48 UTC, githubnameting commented on byzer-lang/zh-cn/installation/containerized_deployment/muti-continer.md
> +获取方式：例如最新的tag为v2.2.1，则使用版本号2.2.1，那么参数应该设置为 `export KOLO_LANG_VERSION=2.1.1`。
KOLO_LANG_VERSION 应该改为 BYZER_LANG_VERSION

2022-02-15 05:52 UTC, ZhengshuaiPENG approved these changes

2022-02-15 05:52 UTC, merged