Add github to submit pr related articles
byzer-org/byzer-doc pull request #205
Opened 2022-02-15 11:12 UTC by kaliGo-Li

Introduce how to submit a PR

2022-02-15 11:17 UTC, hellozepp commented
@ZhengshuaiPENG PTAL

2022-02-15 13:55 UTC, ZhengshuaiPENG requested changes
有一些 comment~
感谢你的第一个 doc PR，恭喜你成为 Byzer Community 的 Contributor~

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +# Github提交PR到Byzer
这个文件路径看起来有空格，会比较容易造成页面之间引用的问题，建议改成 “github-submit-pr.md"

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +![](images/github工作流.png)
文件名尽量避免用中文命名哈~ 建议这里可以改为 ”github-workflow.png"

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +这两部完成之后，现在你的代码已经提交到HEAD，但是还没有同步到你的远端仓库。
中英文之间可以使用空格分隔开，这样可以提供更好的可读性

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +你的资料库中有一个名为一个分支master，其被认为是明确的分支。我们用树枝进行实验，他们承诺之前进行编辑master。
“我们用树枝进行实验，他们承诺之前进行编辑master。” 这句话没有读懂

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +如果其他人修改了master分支，而你在你的分支工作，你可以拉在这些更新。
Line 28 和 Line 29 也没有读的很明白，这样表述可能更好：

如果当你基于 master 创建一个新的分支时，是创建基于当前 master 分支做的一个副本或者快照。 如果有其他人修改了 master 分支，那么你可以通过 `pull` 或者 `rebase` 的方式将 master 分支的修改同步到你的分支

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +## 2.项目
标题和正文之间尽量使用空行隔开

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +### Fork
2.3？

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +这两部完成之后，现在你的代码已经提交到HEAD，但是还没有同步到你的远端仓库。
全篇有不少地方都存在中英文之间没有空格的内容

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +# Github提交PR到Byzer
另外可以在blog 的开头加上一段作者的信息介绍~ better to hive， 可以留名字， github id， 邮箱，兴趣爱好等等，擅长的方向，不限制

2022-02-15 13:55 UTC, ZhengshuaiPENG commented on public/blog/zh-cn/github submit pr.md
> +### Fork
Fork 这个章节最好可以有个图示，可以画一下  远程仓库， 个人fork 远程仓库， 本地仓库之间的关系。 提 PR 的话就是，clone 个人fork 仓库到本地，然后在本地仓库使用 git remote add upstream {源仓库地址}， 接下来的流程就是
 1. git rebase upstream main  ，本地同步远程仓库最新改动
 2. git checkout -b new-branch， 创建一个新的分支准备修改
 3. git add * & git commit，在本地 commit 改动
 4. git push origin new-branch，推送修改分支至自己 fork 的远程仓库
 5. 然后在 github 上发起新的 PR 申请

还有一个是一般如果发现了问题，建议先提 issue， 然后在issue中描述设计和 design， 然后在 PR 的 commit message 中以 #{$issue_number}开头，这样 github 会自动管联 issue 和 PR

2022-02-21 12:55 UTC, ZhengshuaiPENG approved these changes
先 merge 再修改一发

2022-02-21 12:56 UTC, ZhengshuaiPENG commented
Kindly remind that please do not use force push when you submit a PR request

2022-02-21 12:56 UTC, merged