add build-in udf docs
byzer-org/byzer-doc pull request #25
Opened 2021-12-12 10:40 UTC by AdmondGuo

2021-12-12 12:22 UTC, ZhengshuaiPENG requested changes

2021-12-12 12:22 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/udf/built_in_udf/vec.md
> +### array_concat
建议以表格的方式，分成如下几列： 函数 | 用法 | 解释 | 示例

2021-12-12 12:22 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/udf/extend_udf/README.md
> +Kolo 支持使用 Python、Java、Scala 编写UDF/UDAF。无需打包或重启，只需运行注册UDF的Kolo代码，就可以即时生效。极大的方便用户自定义扩展Kolo的功能。
如何动态创建？有没有示例说明

2021-12-13 01:57 UTC, AdmondGuo commented on kolo-lang/zh-cn/udf/extend_udf/README.md
> +Kolo 支持使用 Python、Java、Scala 编写UDF/UDAF。无需打包或重启，只需运行注册UDF的Kolo代码，就可以即时生效。极大的方便用户自定义扩展Kolo的功能。
动态扩展部分还在编写，会在下个commit提上来。

2021-12-13 02:07 UTC, AdmondGuo commented on kolo-lang/zh-cn/udf/built_in_udf/vec.md
> +### array_concat
内置UDF部分的描述还是要尽量详细一些，不然用户很难理解用法。

具体来说，理应包括
1.用法介绍 
2.参数描述 
3.示例。
简单的UDF 1 和 2 可以放在一起。

表格的方式我认为会有两个问题：
- 每一列列宽度有限，展示代码的话会很难看
- md的表格是动态的，很可能后面新增了UDF后某一列宽度会改变，页面显示不专业

另外，我参考了Spark的udf网站：[https://spark.apache.org/docs/latest/api/sql/](https://spark.apache.org/docs/latest/api/sql/)。实际编写的时候，用户也会查询这个网站，我们格式做的相近，也会让用户使用更舒服。

最后，还是因为工程量有点大，改一改又要2小时了（T。T）

2021-12-13 09:58 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/udf/built_in_udf/vec.md
> +### array_concat
可

2021-12-13 09:58 UTC, ZhengshuaiPENG commented on kolo-lang/zh-cn/udf/extend_udf/README.md
> +Kolo 支持使用 Python、Java、Scala 编写UDF/UDAF。无需打包或重启，只需运行注册UDF的Kolo代码，就可以即时生效。极大的方便用户自定义扩展Kolo的功能。
ok

2021-12-13 09:59 UTC, ZhengshuaiPENG approved these changes
LGTM

2021-12-13 09:59 UTC, merged